# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blog_esportivo
      - ENVIRONMENT=production
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_esportivo
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: